### ISSUE TITLE
Auto Complete the whole entry

### ISSUE THREAD

**Issue by Weasy666** [nicmichael/efa#1]
It would be really nice, if the [auto completion](
https://github.com/nicmichael/efa/blob/master/de/nmichael/efa/core/items/ItemTypeStringAutoComplete.java) would check if the entered text is somewhere contained in an entry (like using `textField.getText().toLowerCase().contains("bar".toLowerCase())`) and not just if the entry begins with the entered text. I don't know if this behavior is intended, but at least it's working like that in the efa we are using at our canoeing club.

**Comment by cubitusgh2** [comment]
Solution in https://github.com/nicmichael/efa/pull/73

**Comment by cubitusgh2** [comment]
Fixed with solution in #73
