### ISSUE TITLE
Allow user-specific port for FTP upload

### ISSUE THREAD

**Issue by nicmichael** [nicmichael/efa#13]
http://forum.nmichael.de/viewtopic.php?f=9&t=1159

mein ftp Dienstleister hat den ftp port von 21 auf einen port im Bereich 40000 umgestellt. Wie kann ich bei der Ausgabedatei ftp den Port definieren ?

bisherige Versuche wie

Code: Alles auswählen

ftp:xxx:yyy@zzzz.myfritz.net:43210:/Kilometerliste.csv

- also den Port mit Doppelpunkt an den Host anzufügen - scheiterten leider (connection refused) - auf der Kommandozeile per ftp geht es natürlich, also kein FW-Problem o.ä.

**Comment by cubitusgh2** [comment]
Work in progress with #58

**Comment by cubitusgh2** [comment]
Work in progress with https://github.com/nicmichael/efa/issues/58 
This post is redundant, so it is closed.
