### ISSUE TITLE
EFA#041: Allow to change boat for existing reservations

### ISSUE THREAD

**Issue by nicmichael** [nicmichael/efa#15]
http://forum.nmichael.de/viewtopic.php?f=9&t=1154

da ja Weihnachten vor der Tür steht: Könnte man bei den "Reservierungen bearbeiten" auch einen Wechsel des Boots zulassen ? Ich vermisse die Funktion, wenn die Boote mal wieder umdisponiert werden müssen :roll:

**Comment by cubitusgh2** [comment]
See fix in [MN_EFA_041_BOATRESERVATIONS_COPY_AND_CHANGE_BOAT](https://github.com/cubitusgh2/efa_ksc_replay/tree/MN_EFA_041_BOATRESERVATIONS_COPY_AND_CHANGE_BOAT) which will be included in one of the upcoming releases.

**Comment by cubitusgh2** [comment]
Fixed in efa 2.3.3
