### ISSUE TITLE
Improve boat damage dialog

### ISSUE THREAD

**Issue by nicmichael** [nicmichael/efa#16]
http://forum.nmichael.de/viewtopic.php?f=9&t=1150

Ich habe das Dialogfenster Bootsschäden mal als Anhang mitgeschickt. Ich benutze ein Windows 10 und die efa-Version 2.2.2._40 .

Es sind letztlich zwei Dinge, die ich mir besser wünsche:
1. Ich muss jedes Mal beim Öffnen des Dialogfensters die Spalten mit den Datumsangaben größer ziehen, weil ich sonst nichts lesen kann. Da ja dort immer ein Datum steht, hoffe ich auf eine fest einprogrammierte Anfangsbreite.
2. Ich möchte gerne die behobenen Bootsschäden ausblenden, aber ohne sie zu löschen. Wäre es möglich, hier noch ein Kontrollkästchen hinzuzufügen? Die Farbänderung der Einträge ist schon nett, aber eine kurze Liste ist noch besser.

**Comment by cubitusgh** [comment]
In Arbeit. Mit erledigt wird - Tabellenüberschriften grundsätzlich in fetter Schrift.

**Comment by cubitusgh** [comment]
Gefixt in EFA_0025_BOAT_DAMAGE_LIST_WITH_FILTER

**Comment by cubitusgh2** [comment]
Gefixt in 
Efa 0025 boat damage list with filter replay

Dieser Fix benötigt zusätzlich die Vorarbeiten in
EFA_0017_FILTER_BOATRESERVATIONS_BY_DATE
