### ISSUE TITLE
EFA_0001 Boatstatus is always set to AVAILABLE instead of base status of the boat

### ISSUE THREAD

**Issue by cubitusgh** [nicmichael/efa#2]
If you cancel or finish a session, the boatstatus gets always set to AVAILABLE.

This does not fit to the function of bootshaus that you can set a default status for a boat when it is not on the water.

Use case:
- Boat list in the GUI  of efa bootshaus shall only display the boats which ar available to the public
- Full boat list shall contain public and private boats
- so you configure the default status of the private boats as "invisible"

The bug itself leads to the behaviour that after finishing or cancelling a session with a private boat, it is set back to "available" no matter what default status is set vor that boat.

The expected behaviour is that when you finish or cancel a session, the boat status gets set back to its default status (if the boat is within the list of known boats).

**Comment by cubitusgh** [comment]
This issue is fixed in branch 
https://github.com/cubitusgh/efa_ksc_hannover/tree/EFA_0001_UPDATE_BOATSTATUS_ON_CANCEL

**Comment by nicmichael** [comment]
Closed with https://github.com/nicmichael/efa/commit/8849d280271c49aa7c7ffb4154416752f0fff8a4
