### ISSUE TITLE
Log file rotation by efaCLI leads to failure of logging in efaBoathouse

### ISSUE THREAD

**Issue by cubitusgh** [nicmichael/efa#22]
Based on forum entry: http://forum.nmichael.de/viewtopic.php?f=15&t=1214

When efaCLI detects an efa.log file which is bigger than one megabyte, it moves the efa.log into the backup directory and tries to create a new one. 

EfaBoathouse will not log into the new efa.log file until it is restarted, so all log file entries are lost.

**Comment by cubitusgh** [comment]
Issue is in progress.
See https://github.com/cubitusgh2/efa_ksc_replay/tree/EFA_0027_FIX_EFACLI_LOGROTATE_PROBLEM

**Comment by cubitusgh** [comment]
Created a pull request.
Documented the remaining issues with the solution.

https://github.com/nicmichael/efa/pull/24

**Comment by cubitusgh2** [comment]
Workaround in https://github.com/nicmichael/efa/pull/80

**Comment by cubitusgh2** [comment]
fixed with Workaround in #80
