### ISSUE TITLE
EFA_0002 Hitting ESC in the "abort session" dialogue does abort the session instead of cancelling the abortion

### ISSUE THREAD

**Issue by cubitusgh** [nicmichael/efa#3]
See also:
http://forum.nmichael.de/viewtopic.php?f=15&t=1127

When a user aborts a session, a dialogue is displayed. 
When you hit ESC in this dialogue, the session gets aborted, although the user intended to cancel the abortion.

ESC should work as if the user hit the cancel button.

**Comment by cubitusgh** [comment]
Issue is fixed in 
https://github.com/cubitusgh/efa_ksc_hannover/tree/EFA_0001_UPDATE_BOATSTATUS_ON_CANCEL

**Comment by nicmichael** [comment]
Fixed with https://github.com/nicmichael/efa/commit/3ae3e53353fee9a7c0e488acac5846c7f84fe0fd
