### ISSUE TITLE
NullPointerException after efa 2.3.0_00 update

### ISSUE THREAD

**Issue by nicmichael** [nicmichael/efa#34]
Some clubs are experiencing exceptions:

Folgender Fehler ist aufgetreten:
[20.03.2021 10:58:52] - efaBths - 21596 - ERROR   - EXC001 - java.lang.NullPointerException
de.nmichael.efa.gui.EfaBaseFrame.efaBoathouseFinishSession(EfaBaseFrame.java:4459)
de.nmichael.efa.gui.EfaBaseFrame.setDataForBoathouseAction(EfaBaseFrame.java:4344)
de.nmichael.efa.gui.EfaBoathouseFrame.showEfaBaseFrame(EfaBoathouseFrame.java:1995)
de.nmichael.efa.gui.EfaBoathouseFrame.actionFinishSession(EfaBoathouseFrame.java:2091)
de.nmichael.efa.gui.EfaBoathouseFrame.processListAction(EfaBoathouseFrame.java:1598)
de.nmichael.efa.gui.EfaBoathouseFrame.itemListenerAction(EfaBoathouseFrame.java:1565)
de.nmichael.efa.core.items.ItemTypeList.actionPerformed(ItemTypeList.java:283)
javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
javax.swing.AbstractButton.doClick(AbstractButton.java:376)
javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
java.awt.Component.processMouseEvent(Component.java:6539)
javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
java.awt.Component.processEvent(Component.java:6304)
java.awt.Container.processEvent(Container.java:2239)
java.awt.Component.dispatchEventImpl(Component.java:4889)
java.awt.Container.dispatchEventImpl(Container.java:2297)

Folgender Fehler ist aufgetreten:
[20.03.2021 10:58:57] - efaBths - 21596 - ERROR   - ERR014 - Fahrtende: Die gewählte Fahrt #629 (2-) konnte nicht gefunden werden!

**Comment by nicmichael** [comment]
@tfyh Ich schaue mir das mal an, ob das eventuell mit den efaCloud Aenderungen zusammenhaengen koennte.

**Comment by nicmichael** [comment]
@tfyh Hmm, ich habe jetzt nicht genug Zeit, schaue mir das heute abend an. Du hattest doch etwas an BoatStatus im Zusammenhang mit EntryNo geaendert, oder? Wo genau war diese Aenderung nochmal?

**Comment by nicmichael** [comment]
@tfyh Ah, hab's gefunden: https://github.com/nicmichael/efa/commit/678a59d1f4a96a2fff445252d61c52b315138a62#diff-37a729728a5cc62bdc1255f902c41718427b7ad562f54abdd3d80828e0e41636R4459

**Comment by nicmichael** [comment]
@tfyh Ich habe jetzt als zeitweiligen Workaround https://github.com/nicmichael/efa/commit/7b7039b96590fb7ee64e4a4ebe993154938721cf implementiert (also die Aenderung im Falle von nicht-efaCloud rueckgaengig gemacht). Das kann sicherlich nicht die entgueltige Loesung sein. Koenntest Du Dir das bitte nochmal anschauen und mich daran erinnern, was der Grund fuer Deine Aenderung war und in welche Probleme Du mit dem urpruenglichen Code gelaufen bist?

**Comment by nicmichael** [comment]
Rootcause: Fuer Fahrten mit unbekannten Booten (Booten, die in der Bootsliste nicht existieren) ist item.boat == null, und der Bootsstatus kann nur ueber item.boatStatus abgefragt werden.
Ausserdem ist es moeglich, dass ein Boot "mehrmals gleichzeitig" auf Fahrt ist (natuerlich nicht physisch, aber in efa). Zum Beispiel kann eine Mannschaft eine Fahrt mit einem Boot beginnen, dass gerade von einer anderen Mannschaft vom Wasser getragen wird (aber in efa noch nicht ausgetragen ist). efa erlaubt solche Doppeleintraege, um der neuen Mannschaft zu ermoeglichen, eine Fahrt in efa zu beginnen, obwohl die vorherige Mannschaft ihre Fahrt in efa noch nicht abgeschlossen hat. Andere Situation koennte sein, dass die vorherige Mannschaft vergessen hat, die Fahrt in efa zu beenden. In solchen Faellen wurde item.boat fuer beide Fahrten dasselbe Boot referenzieren und somit item.boat.getBoatStatus().getEntryNo() fuer beide Fahrten dieselbe EntryNo liefern - obwohl die Listeneintraege der Boote auf Fahrt natuerlich zu verschiedenen Fahrtenbucheintraegen gehoeren. WIr muessen also (auch in efaCloud) immer item.boatStatus.getEntryNo() verwenden und verstehen, welche Probleme Du damit hattest (und ob diese sich auf andere Weise loesen lassen).

**Comment by tfyh** [comment]
Hallo Nick,
das Szenario war der Fall, dass eine Fahrt mit einer EntryId angelegt wird, sagen wir die 670, der Server diese Id aber shon vergeben hat und korrigiert, sagen wir auf die 671. Die EntryId ist im Bootsstatus auch hinterlegt, sie muss in beiden gleich sein, damit ich die Fahrt sauber schließen kann. Ich habe etwas gebraucht um den Zusammenhang zu finden udn dann im Rahmen der Tests diese Verweisänderung eingebaut. Der Basistest war: Fahrt öffnen, abbrechen, neue Fahrt öffnen. Weil der Server Ids nicht löscht, sondern nur Datensätze leert, führt das immer zu dem oben geschilderten Konflikt. In dem Testfall geht es nun auch mit der originalen Version. Es ist möglich, dass der Fehler ursächlich an anderer Stelle behoben wurde. Ich habe deswegen die Änderung zurückgebaut und nur einen Kommentar drin gelassen, wenn wir doch irgendwann auf ein Szenario dieser Art stoßen sollten. Ich teste jetzt noch ausführlich und dann gibt es wider einen Pull-Request.
