### ISSUE TITLE
EFA_0003 efa should provide details for an overlapping reservation

### ISSUE THREAD

**Issue by cubitusgh** [nicmichael/efa#4]
When a user creates a new reservation, efa boothaus checks for existing reservations which overlap the new reservation.

In case of an overlapping reservation, a simple error message is displayed that there is an overlapping reservation. But no detail info is provided. This is unconvenient for the user.

The user has to cancel the reservation dialogue, and has to filter the boat reservation list manually to get the info which other reservation is in conflict with the new one.

efa bootshaus should provide more detailed information about the (first) overlapping reservation in the error dialogue.

**Comment by cubitusgh** [comment]
A fix is available at
https://github.com/cubitusgh/efa_ksc_hannover/tree/EFA_0003_DETAILS_FOR_OVERLAPPING_RESERVATION

**Comment by nicmichael** [comment]
Fixed by https://github.com/nicmichael/efa/commit/d7fbae0d6ec3cc92179273d32655b565bbbca424
