### ISSUE TITLE
no decimal signs in EFA 2.3.1_03

### ISSUE THREAD

**Issue by 104mapo** [nicmichael/efa#48]
since changing to EFA 2.3.1_03 on our EfaLive running on our RaspberryPi we lost all decimal signs. 3,52 km became 352 km. The upload to the EFB (Deutscher Kanuverband) is also affected. Changing the values does not help, after restarting EFA all decimal signs are lost again. The windows version is affected as well.

see also the discussion: http://forum.nmichael.de/viewtopic.php?f=15&t=1343

**Comment by nicmichael** [comment]
Fixed with https://github.com/nicmichael/efa/commit/c998e9a568cd7488faf37cdbf83fd60f9d1e8bd1
