### ISSUE TITLE
EFA_0005 switching between boatlist and personlist is defective

### ISSUE THREAD

**Issue by cubitusgh** [nicmichael/efa#5]
How to reproduce this bug:

1. start efa boathouse
2. click on radiobutton "boote"
3. cick on radiobutton "boote"
4. click on radiobutton "personen"
5. click on radiobutton "personen"
6. click on radiobutton "boote"
7. click on any boat in the boatlist
    -> boathouse shows a contextmenue for persons,
    -> the boatlist is optically broken, cannot be used any more.
    -> this condition stays until efa boathouse is restarted

Steps 2 and 3 can be discarded. They show that there is NO problem when the radiobutton for switching to the boatlist is clicked.

**Comment by cubitusgh** [comment]
Fix available at
https://github.com/cubitusgh/efa_ksc_hannover/tree/EFA_0005_SWITCH_BETWEEN_BOATLIST_AND_PERSONLIST

**Comment by nicmichael** [comment]
Fixed with https://github.com/nicmichael/efa/commit/0519bc6e25bf467f1308ede7a5a7b53353ef65b1
