### ISSUE TITLE
EFA: JavaMail libraries outdated

### ISSUE THREAD

**Issue by cubitusgh2** [nicmichael/efa#56]
See forum: http://forum.nmichael.de/viewtopic.php?f=15&t=1326&p=4997

The library for sending mails (plugins/javax.mail.jar) is outdated.
The outdated library wants to initiate TLS 1.1 connections, which are outdated by March 2021.

A new version of the library should be included in future releases of efa.
https://javaee.github.io/javamail/#Download_JavaMail_Release

**Comment by sebko200** [comment]
fixed in Version 2.3.2_01 (Release Date 28.10.2022)

**Comment by mechanicalman1** [comment]
![Screenshot_2022-12-26-22-16-44-385_com realvnc viewer android](https://user-images.githubusercontent.com/59438299/209584077-22de1334-d404-4d6b-bfbf-3885a28454c2.jpg)

![Screenshot_2022-12-26-22-16-17-881_com realvnc viewer android](https://user-images.githubusercontent.com/59438299/209584090-b15a3d59-dd75-4d9b-997f-3d5652c6c8b0.jpg)

I updated to 2.3.2_01.
Library remains outdated.
Is this really fixed?

**Comment by cubitusgh** [comment]
Yes, it is fixed.
The javamail library is the newest (compile date somewhere in 2018).
The glitch is that the information in this dialog is read from a plugins.xml file which has not been updated.

So, opening a new Issue to update the plugins.xml contents.

**Comment by cubitusgh2** [comment]
Fixed with release 2.3.2
