### ISSUE TITLE
EFA#037 / EFA: Update FTP client für SFTP/FTPS support, custom FTP(s) port number

### ISSUE THREAD

**Issue by cubitusgh2** [nicmichael/efa#58]
**FTP as a non-secure protocol is somewhat outdated.**
http://forum.nmichael.de/viewtopic.php?f=9&t=1112
- SFTP or FTPs should be supported

**Custom FTP port number:**
- user should be able to provide a custom FTP(s) port number 
http://forum.nmichael.de/viewtopic.php?f=9&t=1159#p4646

**Comment by cubitusgh2** [comment]
This issue is in the works, see https://github.com/cubitusgh2/efa_ksc_replay/tree/MN_EFA_037_SFTP_FTPS_SUPPORT
- configurable FTP port
- support for SFTP
- support for FTPS

Backwards compatible to the current FTP solution.
Not yet tested.

**Comment by cubitusgh2** [comment]
Fixed with efa 2.4.0

**Comment by Zephyr82** [comment]
Awesome! :)
