### ISSUE TITLE
BUG: New Trip: Person list contains invalid persons (since version >2.3.0)

### ISSUE THREAD

**Issue by cubitusgh2** [nicmichael/efa#62]
http://forum.nmichael.de/viewtopic.php?f=15&t=1344

Fehler besteht seit Version 2.3.2

Forumeintrag:
Diese Woche probeweise ein Update von 2.3.0 auf 2.3.2 durchgeführt.
Das aktuell bei den Namensvorschlagen auch "derzeit ungültige" Datensätze vorgeschlagen werden ist in unserem Vereinsbetrieb jedoch so störend, dass ich wieder auf 2.3.0 zurückgegangen bin.

Auch ich möchte gerne noch einmal diesen Fehler hervorheben. Bis dies behoben ist werden wir keine aktuellere Version als 2.3.0 nutzen können.

Viele Grüße und vielen Dank,

**Comment by nicmichael** [comment]
@cubitusgh2 Hast Du dieses Problem auch beobachtet? Ich kann das Problem bei mir nicht nachstellen.

**Comment by cubitusgh2** [comment]
Nein, ich konnte dieses Problem bei mir nicht nachstellen.

**Comment by nicmichael** [comment]
Fixed with https://github.com/nicmichael/efa/commit/522929d85a12ee98a864ffaf551e79be8ea080a4
