### ISSUE TITLE
BUG: efaCloud(?): invalid crew members get name "archiveID", problems with "Fahrtabzeichen"

### ISSUE THREAD

**Issue by cubitusgh2** [nicmichael/efa#63]
http://forum.nmichael.de/viewtopic.php?f=15&t=1354

-----

Hallo Leute,

bei der Auswerung des Fahrtenbuchs ist mir bei den Vorjahren aufgefallen, dass ungültige Ruderer in der EFA-Datenbank die Bezeichnung "archiveID:", ergänzt mit einer Zahl erhalten haben. Ich kann also bei ungültigen Ruderern nicht mehr nachvollziehen wer das Namentlich war.
Da ich EFA seit 2005 nutze und auch die entsprechenden Fahrtenbücher in EFA habe ist das sehr unglücklich.

Ruderer werden von mir als z.B. bei Vereinsaustritt als ungültig gesetzt.
Im Verein nutzen wir EFA Cloud. Im Bootshaus nutzen wir efaLive und zu Hause nutze ich efa mit Mint und Windows. Das Problem ist im Bootshaus und auf Windows aufgetreten.

Wie kann ich die Namen wiederherstellen?

Viele Grüße

------
Beim Upload der Fahrtenabzeichen überraschte mich das Problem der ungültigen Ruderer. Diese Personen sind nicht mehr Mitglied und daher wurde der Gültigkeitszeitraum entsprechend mit einem Enddatum versehen. Beim Fahrtenabzeichen hat man das Glück, den Eintrag aufzurufen und kann zu den "achiveID:xxx" den korrespondierenden Namen herausfinden.
Ein Blick in die "Personen" Liste hat es mich glatt vom Hocker geholt. Da befinden sich 1063 ungültige Eintragungen. Wie im vorherigen Blogeintrag ist die Frage, wie kann das behoben werden? Aus den o.g. Fahrtenabzeichen-Liste kann ich die wenigen ungültigen Einträge durch die archiveID:xxx zuweisen. Aber der Rest? Wohl nur über ein hoffentlich vorhandenes Backup der Mitgliederliste. In der Hoffnung, dass efa da nicht meckert.

Woher stammen diese Fehleinträge? Steht das im Zusammenhang mit den Updates und/oder mit der Nutzung der Cloudfunktion?

Das Forum zeigt auf, dass die Problemfälle in der letzten Zeit sich häufen. Die Lösungsvorschläge halten sich aber in homöopathischen Dosen.
Da ist es kein Wunder, das der Frust so langsam steigt.
Gruß

**Comment by tfyh** [comment]
die archiveID wird von efaCloud eingefügt. Die EU Datenschutzgrundverordnung ist der Grund: wer im Web Daten hostet, tut gut daran, auch die Konformität mit dem Datenschutz im Blick zu haben. Wer das nicht will, sollte m. E. die Finger von efaCloud lassen, denn grobe Mängel im Datenschutz sind strafbewehrt. (Das gilt übrigens auch für efa selbst, kann da aber kaum kontrolliert werden.)

Der Datenschutz fordert, dass Daten gelöscht werden, wenn es keinen Verwendungszweck mehr gibt. Es ist schwer nachvollziehbar, zu welchem Zweck ein Verein Daten von ehemaligen Mitgliedern halten sollte. Ich würde nicht wollen, dass jemand bequem von zu Hause meine sportlichen Leistungen nachlesen kann auch Jahre nachdem ich den Verein verlassen habe. Die Archivierung ist ein Kompromiss, denn sie löscht die Daten im Moment noch nicht einmal, sondern verlagert sie in ein Archiv, macht sie also schwerer zugänglich.

Die Grundeinstellung archiviert Bewegungsdaten (Fahrten, Nachrichten, Bootsschäden etc) nach 720 Tagen (= 2 Jahre), Personen nach 1810 Tagen (= 5 Jahre). Die Einstellung kann geändert werden in efaCloud unter "efaCloud einstellen > Parameter > Alter in Tagen für die Archivierungⓘ von Datensätzen" (ganz unten). Erläuterungen findet ihr mit dem ⓘ. Um die Archivierung abzustellen muss ein entsprechend hoher Wert eingetragen werden, z.B. 20000 (= 55 Jahre)

Bereits archivierte Datensätze können wieder hergestellt werden mittels: efaCloud > efa Daten > Archivdaten wiederherstellen.

Wenn die archiveID zu Fehlern in efa führen sollte, bin ich für Hinweise immer dankbar. In diesem Thread kann ich funktionale Fehler allerdings nicht sehen.

Viele Grüße
Martin

**Comment by cubitusgh2** [comment]
Siehe vorherigen Kommentar: ist ein Feature, kein Bug.
Der Thread im EFA-Forum ist ebenfalls kommentiert worden.
Daher schließen dieses Bugs.
