### ISSUE TITLE
Bug: efaBASE: Person list looses persons after late entry of trips (since 2.3.0)

### ISSUE THREAD

**Issue by cubitusgh2** [nicmichael/efa#67]
See forum entry http://forum.nmichael.de/viewtopic.php?f=15&t=1345

Bug occurs only in efaBASE and has its origin in https://github.com/nicmichael/efa/pull/44 .
This feature had the intention of removing persons from the autocomplete list once the person is assigned as a crew member of a trip (with a boat that allows multiple crew members). This shall avoid entering the same person on diffrent crew items of the same trip.

This works well in efaBoatHouse as the late entry form gets re-initialized every time a late entry is initiated.
In efaBase, there is no re-initialization of the main screen after saving a late entry.

So, the person autocomplete list shows less persons after each late entry.

**Comment by nicmichael** [comment]
Fixed with https://github.com/nicmichael/efa/commit/522929d85a12ee98a864ffaf551e79be8ea080a4
