### ISSUE TITLE
Überschreiben von Fahrten in efaCloud bei Fahrtenbuchwechsel und Zusammenführen von Datensätzen

### ISSUE THREAD

**Issue by tfyh** [nicmichael/efa#75]
Für die Synchronisation von efa und efaCloud verwendet efaCloud die Information des aktuellen Fahrtenbuchs. In efaCloud gibt es nicht eine Tabelle pro Fahrtenbuch, sondern eine Tabelle mit allen Fahrtenbüchern in einer, deswegen wird dort das zusätzliche Datenfeld "Logbookname" geschrieben, um eine Zuordnung möglich zu machen.
Bei einem Wechsel des Fahrtenbuchs ohne Neustart führt das dazu, dass ein Fahrt-Datensatz mit dem falschen Fahrtenbuchnamen versehen wird und dadurch efaCloud die Fahrt in das falsche Fahrtenbuch schreibt. Dadurch können Fahrten sogar überschrieben werden.
Der Fehler wirkt sich auch aus beim Zusammenführen von Datensätzen, etwa Personen, Booten oder Zielen, weil dabei alle Fahrtenbücher geöffnet und korrigiert werden. efaCloud bekommt den dazugehörigen Fahrtenbuchweschel nicht mit und schreibt alle Änderungen in das aktuelle Fahrtenbuch.
Diese Fehler synchronisieren sich zwar in der Regel nicht zurück in efa, weil die Fahrten dann nicht mehr in die Periode des Fahrtenbuchs passen, aber wenn es mehrere Fahrtenbücher mit derselben Periode gibt, kann auch eine Propagation der Fehler zurück in efa passieren. In jedem Fall erfordert das Auseinanderlaufen der Daten von efa und efaCloud erhebliche Nacharbeiten durch den Verwalter.

**Comment by cubitusgh2** [comment]
Gefixt mit efa 2.3.3_00 (29.09.2023)
