### ISSUE TITLE
efaCloud Synchronisationsabweichungstoleranz zu eng

### ISSUE THREAD

**Issue by tfyh** [nicmichael/efa#76]
Es ist gerade im ersten Quartal der Einführung von efaCloud immer mal wieder zu technischen Problemen bei der Synchronisation gekommen. Um zu vermeiden, dass komplett falsche Datensätze in efaCloud bei der Synchronisation in efa zurückgeschrieben werden, war daher eine Prüfung in efa ergänzt worden, die eine Aktualisierung von Datensätzen durch den Server nur zulässt, wenn der bestehende Datensatz und der vom Server gelieferte Datensatz nur in einer begrenzten Zahl von Datenfeldern voneinander abweichen. Es hat sich herausgestellt, dass das auch dazu führt, das "richtige" Aktualisierungen nicht an die Clients weitergegeben werden, weil die Begrenzung zu eng war für manche Tabellen.
Dadurch haben Clients unterschiedliche Daten, was die Nutzer wiederum zu der Wahrnehmung führt, dass die Synchronisation fehlerhaft ist.
Deswegen muss die Synchronisationsabweichungstoleranz tabellenspezifisch etwas weiter gefasst werden.

**Comment by cubitusgh2** [comment]
Gefixt mit efa 2.3.3_00 (29.09.2023)
